// Structured log constants (clean separate file)
// Prefer importing this (`require('../config/logConstants')`) from controllers.

const LOGCONSTANTS = {
  actions: {
    user: {
      CREATE_USER: "CREATE USER",
      LOGIN: "LOGIN",
      LOGOUT: "LOGOUT",
      DELETE_USER: "DELETE USER",
    },
    achievements: {
      CREATE_ACHIEVEMENT: "CREATE ACHIEVEMENT",
      UPDATE_ACHIEVEMENT: "UPDATE ACHIEVEMENT",
      DELETE_ACHIEVEMENT: "DELETE ACHIEVEMENT",
    },
    news: {
      CREATE_NEWS: "CREATE NEWS",
      UPDATE_NEWS: "UPDATE NEWS",
      DELETE_NEWS: "DELETE NEWS",
    },
    // officials: { Hardcoded in the frontend, temporarily removed from here
    //   CREATE_OFFICIAL: 'CREATE OFFICIAL',
    //   UPDATE_OFFICIAL: 'UPDATE OFFICIAL',
    //   DELETE_OFFICIAL: 'DELETE OFFICIAL',
    // },
    pageContents: {
      CREATE_PAGE_CONTENTS: "CREATE PAGE CONTENTS",
      UPDATE_PAGE_CONTENTS: "UPDATE PAGE CONTENTS",
    },

    announcements: {
      CREATE_ANNOUNCEMENT: "CREATE ANNOUNCEMENT",
      UPDATE_ANNOUNCEMENT: "UPDATE ANNOUNCEMENT",
      DELETE_ANNOUNCEMENT: "DELETE ANNOUNCEMENT",
      TOGGLE_PUBLISH_ANNOUNCEMENT: "TOGGLE PUBLISH ANNOUNCEMENT",
    },

    records: {
      CREATE_RECORD: "CREATE RECORD",
      UPDATE_RECORD: "UPDATE RECORD",
    },
    reports: {
      CREATE_REPORT: "CREATE REPORT",
      UPDATE_REPORT: "UPDATE REPORT",
      DELETE_REPORT: "DELETE REPORT",
      ADD_COMMENTS: "ADD COMMENTS",
      UPDATE_REPORT_STATUS: "UPDATE REPORT STATUS",
    },
    officials: {
      CREATE_OFFICIAL: "CREATE OFFICIAL",
      UPDATE_OFFICIAL: "UPDATE OFFICIAL",
      DELETE_OFFICIAL: "DELETE OFFICIAL",
      TOGGLE_OFFICIAL_STATUS: "TOGGLE OFFICIAL STATUS",
      REORDER_OFFICIALS: "REORDER OFFICIALS",
    },
    barangayInfo: {
      CREATE_BARANGAY_INFO: "CREATE BARANGAY INFO",
      UPDATE_BARANGAY_INFO: "UPDATE BARANGAY INFO",
      UPDATE_BARANGAY_DEMOGRAPHICS: "UPDATE BARANGAY DEMOGRAPHICS",
      UPDATE_BARANGAY_CONTACT: "UPDATE BARANGAY CONTACT",
      UPDATE_BARANGAY_ADDRESS: "UPDATE BARANGAY ADDRESS",
      UPDATE_BARANGAY_SOCIAL_MEDIA: "UPDATE BARANGAY SOCIAL MEDIA",
      DELETE_BARANGAY_INFO: "DELETE BARANGAY INFO",
    },
    services: {
      CREATE_SERVICE: "CREATE SERVICE",
      UPDATE_SERVICE: "UPDATE SERVICE",
      DELETE_SERVICE: "DELETE SERVICE",
      TOGGLE_SERVICE_STATUS: "TOGGLE SERVICE STATUS",
      REORDER_SERVICES: "REORDER SERVICES",
    },
    faqs: {
      CREATE_FAQ: "CREATE FAQ",
      UPDATE_FAQ: "UPDATE FAQ",
      DELETE_FAQ: "DELETE FAQ",
      TOGGLE_FAQ_PUBLISH: "TOGGLE FAQ PUBLISH",
      REORDER_FAQS: "REORDER FAQS",
    },
    banners: {
      CREATE_BANNER: "CREATE BANNER",
      UPDATE_BANNER: "UPDATE BANNER",
      DELETE_BANNER: "DELETE BANNER",
      TOGGLE_BANNER_STATUS: "TOGGLE BANNER STATUS",
      REORDER_BANNERS: "REORDER BANNERS",
    },
    contactMessages: {
      SUBMIT_CONTACT_MESSAGE: "SUBMIT CONTACT MESSAGE",
      UPDATE_MESSAGE_STATUS: "UPDATE MESSAGE STATUS",
      UPDATE_MESSAGE_PRIORITY: "UPDATE MESSAGE PRIORITY",
      ASSIGN_MESSAGE: "ASSIGN MESSAGE",
      ADD_MESSAGE_RESPONSE: "ADD MESSAGE RESPONSE",
      ADD_INTERNAL_NOTE: "ADD INTERNAL NOTE",
      MARK_MESSAGE_AS_SPAM: "MARK MESSAGE AS SPAM",
      TOGGLE_MESSAGE_ARCHIVE: "TOGGLE MESSAGE ARCHIVE",
      DELETE_CONTACT_MESSAGE: "DELETE CONTACT MESSAGE",
    },
  },
};

module.exports = { LOGCONSTANTS };
